# Generated by Django 5.2.11 on 2026-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
